<?php

use Drupal\quizz_scale\Entity\Collection;
use Drupal\quizz_scale\Entity\CollectionController;

require_once dirname(__FILE__) . '/quizz_scale.hooks.inc';

/**
 * @return \Drupal\quizz_scale\Entity\CollectionController
 */
function quizz_scale_collection_controller() {
  return entity_get_controller('scale_collection');
}

/**
 * Load collection entity.
 *
 * @param int $id
 * @return \Drupal\quizz_scale\Entity\Collection|null
 */
function quizz_scale_collection_load($id) {
  return entity_load_single('scale_collection', $id);
}

/**
 * Access callback for scale_collection entity.
 * @param string $op
 * @param Collection $collection
 * @param stdClass $account
 * @return bool
 */
function quizz_scale_collection_access_callback($op, $collection = NULL, $account = NULL) {
  return user_access('Edit global presets', $account);
}
