<?php

use Drupal\scale\Entity\Collection;
use Drupal\scale\Entity\CollectionController;

require_once dirname(__FILE__) . '/scale.hooks.inc';

/**
 * @return CollectionController
 */
function scale_collection_controller() {
  return entity_get_controller('scale_collecction');
}

/**
 * Access callback for scale_collection entity.
 * @param string $op
 * @param Collection $collection
 * @param stdClass $account
 * @return bool
 */
function scale_collection_access_callback($op, $collection = NULL, $account = NULL) {
  return user_access('Edit global presets', $account);
}
