<?php

/**
 * Implements hook_quiz_question_info().
 */
function quiz_page_quiz_question_info() {
  return array(
      'quiz_page' => array(
          'name'              => t('@quiz page', array('@quiz' => QUIZZ_NAME)),
          'description'       => t('Quiz pages allow you display questions across multiple pages.'),
          'question provider' => 'QuizPagesQuestion',
          'response provider' => 'QuizPagesResponse',
          'module'            => 'quizz_question', // All wrapper functions are in that module.
      ),
  );
}
